# Generated by Django 6.0 on 2025-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=100)),
                ('focus', models.CharField(choices=[('Sports', 'Sports'), ('Sciences', 'Sciences'), ('Languages', 'Languages')], max_length=100)),
                ('students', models.IntegerField(max_length=1000)),
                ('uniform', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Grey', 'Grey')], max_length=100)),
                ('classteacher', models.CharField(max_length=100)),
            ],
        ),
    ]
