# Generated by Django 6.0 on 2025-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='focus',
            field=models.CharField(choices=[('Sciences', 'Sciences'), ('Languages', 'Languages'), ('Sports', 'Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='stream',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='uniform',
            field=models.CharField(choices=[('White', 'White'), ('Grey', 'Grey'), ('Black', 'Black')], max_length=100),
        ),
    ]
