# Generated by Django 6.0 on 2025-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroommodel_focus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=100)),
                ('focus', models.CharField(choices=[('Sports', 'Sports'), ('Sciences', 'Sciences'), ('Languages', 'Languages')], max_length=100)),
                ('students', models.IntegerField()),
                ('uniform', models.CharField(choices=[('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White')], max_length=100)),
                ('classteacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassRoomModel',
        ),
    ]
