# Generated by Django 6.0 on 2025-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(choices=[('forest', 'Forest'), ('mountains', 'Mountains'), ('home', 'Home'), ('ocean', 'Ocean'), ('desert', 'Desert'), ('savannah', 'Savannah'), ('wetlands', 'Wetlands'), ('jungle', 'Jungle')], max_length=100),
        ),
    ]
