# Generated by Django 6.0 on 2025-12-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
